### ISSUE TITLE
RecSys I/O TODO - June 2015

### ISSUE THREAD

**Issue by suranah** [abhijithch/RecSys.jl#11]
- [ ] create code skeleton for I/O
- [ ] add read input for various formats, output as a DataFrame with common structure as Internal Representation (IR)
- [ ] create sparse matrix for SVD from IR
- [ ] wrapper functions
- [ ] evaluation and validation using MLBase
- [ ] adding I/O macros
